daydayseafood/buyer/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('index.html', views.index),
    re_path('^$', views.index),
    path('list.html', views.listpage),
    path('detail.html', views.detail),
    path('cart.html', views.cart),
    path('place_order.html', views.place_order),
    path('user_center_site.html', views.user_center_site),
    path('user_center_info.html', views.user_center_info),
    path('user_center_order.html',views.user_center_order),
    path('alipay', views.alipay)
]

daydayseafood/daydayseafood/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', views.index),
    path('index.html',views.index),
    path('register.html', views.register),
    path('login.html', views.login),
    path('seller/', include('seller.urls')),
    path('buyer/', include('buyer.urls'))
]

daydayseafood/buyer/models.py
from django.db import models

from seller.models import LoginUser, Goods, GoodsType


# Create your models here.
##############################
# 购物车模型
##############################
class Cart(models.Model):
    goods = models.ForeignKey(to=Goods, on_delete=models.CASCADE)
    goods_number = models.IntegerField(verbose_name="商品的数量")
    # goods_total = models.FloatField(verbose_name="商品的小计")
    cart_user = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE, verbose_name="买家")

    class Meta:
        db_table = "cart"


ORDER_STATUS = (
    (1, "未支付"),
    (2, "已支付"),
    (3, "待发货"),
    (4, "已发货"),
    (5, "拒收"),
    (6, "已完成"),
)


##############################
# 订单模型
##############################
class PayOrder(models.Model):
    order_number = models.CharField(max_length=8, null=True, verbose_name="订单号")
    order_date = models.DateField(auto_now=True, verbose_name="订单创建时间")
    order_status = models.IntegerField(choices=ORDER_STATUS, verbose_name="订单状态")
    order_address = models.CharField(max_length=1024, verbose_name="送货地址")
    order_user = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE, verbose_name="买家")

    class Meta:
        db_table = "pay_order"


##############################
# 订单商品模型
##############################
class OrderInfo(models.Model):
    order = models.ForeignKey(to=PayOrder, on_delete=models.CASCADE)
    goods = models.ForeignKey(to=Goods, on_delete=models.CASCADE)
    goods_price = models.FloatField(verbose_name="商品的单价")
    # store = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE, verbose_name="卖家")
    goods_count = models.IntegerField(verbose_name="购买的单品的数量")
    goods_total_price = models.FloatField(verbose_name="购买的单品的总金额")

    class Meta:
        db_table = "order_info"


USERSITE_STATUS = (
    (1, "默认地址"),
    (2, "历史地址"),
    (3, "禁用地址")
)


##############################
# 用户地址管理
##############################
class UserSite(models.Model):
    user = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE, verbose_name="用户")
    username = models.CharField(max_length=32, verbose_name="收货人")
    sitearea = models.TextField(verbose_name="收货地址")
    code = models.CharField(max_length=8, verbose_name="邮政编码")
    phone = models.CharField(max_length=11, verbose_name="电话号码")
    status = models.IntegerField(choices=USERSITE_STATUS, default=1, verbose_name="地址状态")

    class Meta:
        db_table = "user_site"


##############################
# 最近浏览记录每个用户保存5条记录
##############################
class LookHistory(models.Model):
    user = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE, verbose_name="浏览用户")
    goods = models.ForeignKey(to=Goods, on_delete=models.CASCADE, verbose_name="浏览商品")
    datatime = models.DateTimeField(auto_now=True, verbose_name="浏览时间")

    class Meta:
        db_table = "look_history"

daydayseafood/seller/models.py
from django.db import models

# Create your models here.

###########################
# 注册用户信息
##########################
GENDER_STATUS = (
    (0, "女"),
    (1, "男")
)
USER_TYPE = (
    (0, "卖家"),
    (1, "买家")
)


class LoginUser(models.Model):
    email = models.EmailField(verbose_name="邮箱")
    password = models.CharField(max_length=32, verbose_name="密码")
    username = models.CharField(max_length=32, verbose_name="用户名", default="")
    phone_number = models.CharField(max_length=11, verbose_name="手机号", null=True, blank=True)
    age = models.IntegerField(verbose_name="年龄", null=True, blank=True)
    gender = models.IntegerField(choices=GENDER_STATUS, verbose_name="性别", default=1)
    address = models.TextField(verbose_name="地址", null=True, blank=True)
    photo = models.ImageField(upload_to="img/user/", default="img/user/touxiang.png", verbose_name="图片")
    user_type = models.IntegerField(choices=USER_TYPE, default=1, verbose_name="用户身份")  ## 0 代表卖家 1代表买家

    def __str__(self):
        return self.username

    class Meta:
        db_table = "loginuser"


###########################
# 商品分类
###########################
class GoodsType(models.Model):
    type_label = models.CharField(max_length=32, verbose_name="类型标签")
    type_description = models.TextField(verbose_name="类型的描述")
    type_picture = models.ImageField(max_length=64, upload_to="img/goodstype/", verbose_name="类型的图片")

    def __str__(self):
        return self.type_description

    class Meta:
        db_table = "goods_type"


GOODS_STATUS = (
    (0, "下架"),
    (1, "在售")
)


###########################
# 商品信息
###########################
class Goods(models.Model):
    goods_number = models.CharField(max_length=11, verbose_name="商品编号")
    goods_name = models.CharField(max_length=32, verbose_name="商品名字")
    goods_price = models.FloatField(verbose_name="商品价格")
    goods_count = models.IntegerField(verbose_name="商品数量")
    goods_location = models.CharField(max_length=32, verbose_name="商品产地")
    goods_safe_date = models.IntegerField(verbose_name="商品保质期")
    goods_pro_time = models.DateTimeField(auto_now=True, verbose_name="生成日期")
    goods_status = models.IntegerField(choices=GOODS_STATUS, verbose_name="商品状态", default=1)  ## 0代表下架  1 代表在售
    goods_picture = models.ImageField(upload_to="img/goods/", default="img/1.jpg", verbose_name="商品的图片")
    goods_description = models.TextField(default="good goods", verbose_name="商品的描述")
    goods_type = models.ForeignKey(to=GoodsType, on_delete=models.CASCADE)
    goods_store = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.goods_name

    class Meta:
        db_table = "goods"

daydayseafood/buyer/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

from .models import *


# Create your views here.

def isbuyerlogin(func):
    def islogin(request, *args, **kwargs):
        cookie_email = request.COOKIES.get('email')
        session_email = request.session.get('email')
        if cookie_email and session_email and LoginUser.objects.filter(email=session_email).exists():
            user = LoginUser.objects.filter(email=session_email).first()
            response = func(request, user, *args, **kwargs)
            return response
        return HttpResponseRedirect('/login.html')

    return islogin


@isbuyerlogin
def index(request, user):
    params = {
        'page_title': '天天生鲜 - 首页',
        'user': user,
        'goods_type': GoodsType.objects.all()
    }

    return render(request=request, template_name='index.html', context=params)


@isbuyerlogin
def listpage(request, user):
    if request.method == "GET":
        type_description = request.GET.get("type")
        if type_description:
            params = {
                'page_titile': '天天生鲜 - 商品列表',
                'user': user,
                'this_type': GoodsType.objects.filter(type_description=type_description).first(),
                'goods_type': GoodsType.objects.all(),
            }
            return render(request, 'list.html', params)
    return HttpResponseRedirect('/buyer/index.html')


@isbuyerlogin
def detail(request, user):
    params = {
        'page_title': '天天生鲜 - 商品详情',
        'user': user
    }
    if request.method == "POST":
        pass
    elif request.method == "GET":
        id = request.GET.get('id')
        goods = Goods.objects.filter(id=id).first()
        if goods:
            params.update({
                'goods': goods,
                'goods_type': GoodsType.objects.all()
            })
            if LookHistory.objects.filter(user=user, goods_id=id).exists():
                LookHistory.objects.filter(user=user, goods_id=id).delete()
            if LookHistory.objects.filter(user=user).count() > 4:
                LookHistory.objects.filter(user=user).first().delete()
            LookHistory.objects.create(user=user, goods_id=id)
            return render(request, 'detail.html', params)
    return HttpResponseRedirect('/index.html')


@isbuyerlogin
def cart(request, user):
    from django.http import JsonResponse, QueryDict
    from django.db.models import F
    import json, time
    result = {
        'code': 1000,
        'msg': '成功',
        'data': ''
    }
    if request.method == "POST":
        data = json.loads(request.POST.get("data"))
        print(data)
        if data:
            payorder = PayOrder()
            user_site = UserSite.objects.filter(user=user, status=1).first()
            if user_site:
                payorder.order_address = f"{user_site.sitearea} ({user_site.username} 收) {user_site.phone}"
            payorder.order_date = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            payorder.order_status = 1
            payorder.order_total = None
            payorder.order_user = user
            payorder.save()
            payorder.order_number = payorder.id + int(56000000)
            payorder.save()
            for i in data:
                if i['id'] and i['num'] and Goods.objects.filter(id=i['id']).exists():
                    orderinfo = OrderInfo()
                    orderinfo.order = payorder
                    orderinfo.goods = Goods.objects.filter(id=i['id']).first()
                    orderinfo.goods_count = i['num']
                    orderinfo.goods_price = Goods.objects.filter(id=i['id']).first().goods_price
                    orderinfo.goods_total_price = float(i['num']) * Goods.objects.filter(id=i['id']).first().goods_price
                    orderinfo.save()
                    cart = Cart.objects.filter(cart_user=user, goods_id=i['id'])
                    if cart:
                        cart.delete()
            result["url"] = "/buyer/place_order.html"
            return JsonResponse(data=result, json_dumps_params={'ensure_ascii': False})
    elif request.method == "DELETE":
        delete = QueryDict(request.body)
        id = delete.get('id')
        if id and Cart.objects.filter(goods_id=id, cart_user=user).exists():
            Cart.objects.filter(goods_id=id, cart_user=user).delete()
            result['msg'] = '删除成功'
            result['data'] = Goods.objects.filter(id=id).first().goods_name
            return JsonResponse(data=result, json_dumps_params={'ensure_ascii': False})
    elif request.method == "PUT":
        put = QueryDict(request.body)
        id = put.get('id')
        num = put.get('num')
        if id and Goods.objects.filter(id=id).exists():
            if num is None:
                if Cart.objects.filter(goods_id=id, cart_user=user).exists():
                    Cart.objects.filter(goods_id=id, cart_user=user).update(goods_number=F('goods_number') + 1)
                else:
                    Cart.objects.create(goods_id=id, goods_number=1, cart_user=user)
                result['msg'] = "添加成功"

            elif Cart.objects.filter(goods_id=id, cart_user=user).exists():
                if int(num) == 0:
                    Cart.objects.filter(goods_id=id, cart_user=user).delete()
                    result['msg'] = '删除成功'
                else:
                    Cart.objects.filter(goods_id=id, cart_user=user).update(goods_number=int(num))
                    result['msg'] = '修改成功'
            else:
                Cart.objects.create(goods_id=id, goods_number=int(num), cart_user=user)
                result['msg'] = "添加成功"
            result['data'] = Cart.objects.filter(cart_user=user, goods_id=id).first().goods_number
            response = JsonResponse(data=result, json_dumps_params={'ensure_ascii': False})
            response['Access-Control-Allow-Origin'] = '*'
            return response
    elif request.method == "GET":
        params = {
            'page_title': '天天生鲜 - 购物车',
            'user': user
        }
        return render(request, 'cart.html', params)

    result['code'] = 4000
    result['msg'] = '失败'
    return JsonResponse(data=result, json_dumps_params={'ensure_ascii': False})


@isbuyerlogin
def place_order(request, user: LoginUser):
    from buyer import other
    import json
    if request.method == "POST":
        data = request.POST.get("data")
        data = json.loads(data)[0]
        order = other.Alipay()
        url = order.orders(data, user)
        print(url)
        return HttpResponse(url)
        # return HttpResponseRedirect("/index.html")
    upay_order = user.payorder_set.filter(order_status=1).last()
    user_site = UserSite.objects.filter(user=user, status=1).first()
    upay_order.order_address = f"{user_site.sitearea} ({user_site.username} 收) {user_site.phone}"
    upay_order.save()
    params = {
        "page_title": "天天生鲜 - 结算",
        "user": user,
        "upay_order": upay_order
    }
    return render(request, 'place_order.html', params)


@isbuyerlogin
def user_center_site(request, user: LoginUser):
    params = {
        'page_title': '天天生鲜 - 地址管理',
        'user': user
    }
    if request.method == "POST":
        data = request.POST
        username = data.get("username")
        sitearea = data.get("sitearea")
        code = data.get("code")
        phone = data.get("phone")
        if username and sitearea and code and phone:
            if UserSite.objects.filter(user=user, status__in=[1, 2]).exists():
                UserSite.objects.filter(user=user, status__in=[1, 2]).update(status=2)
            UserSite.objects.create(user=user, username=username, sitearea=sitearea, code=code, phone=phone)
    elif request.method == "GET":
        id = request.GET.get("id")
        if id and UserSite.objects.filter(user=user, id=id).exists():
            UserSite.objects.filter(user=user, status=1).update(status=2)
            UserSite.objects.filter(user=user, id=id).update(status=1)
    cur_usersite = UserSite.objects.filter(user=user, status=1).first()
    his_usersite = UserSite.objects.filter(user=user, status=2).all()
    params.update(
        {
            'cur_usersite': cur_usersite,
            'his_usersite': his_usersite
        }
    )
    return render(request, "user_center_site.html", params)


@isbuyerlogin
def user_center_info(request, user: LoginUser):
    params = {
        'page_title': '天天生鲜 - 用户信息',
        'user': user,
        'cur_usersite': user.usersite_set.filter(status=1).first(),
        'look_history': user.lookhistory_set.order_by("-datatime").all()
    }
    return render(request, "user_center_info.html", params)


@isbuyerlogin
def user_center_order(request, user: LoginUser):
    params = {
        'page_title': '天天生鲜 - 订单中心',
        'user': user,
        'order': user.payorder_set.all()
    }
    return render(request=request, template_name="user_center_order.html", context=params)


def alipay(request):
    print("==================================")
    print("method:\n", request.method)
    print("headers:\n", request.headers)
    print("body:\n", request.body)
    print("scheme:\n", request.scheme)
    print('remote_addr',request.META.get("REMOTE_ADDR"))
    return HttpResponse("付款成功")

daydayseafood/buyer/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    {% include 'block/header.html' %}

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>

    <div class="total_count">全部商品<em>{{ user.cart_set.count }}</em>件</div>
    <ul class="cart_list_th clearfix">
        <li class="col01">商品名称</li>
        <li class="col02">商品单位</li>
        <li class="col03">商品价格</li>
        <li class="col04">数量</li>
        <li class="col05">小计</li>
        <li class="col06">操作</li>
    </ul>
    {% for i in user.cart_set.all %}
        <ul class="cart_list_td clearfix" id="{{ i.goods.id }}">
            <li class="col01"><input type="checkbox" name="" checked onclick="refresh()"></li>
            <li class="col02"><img src="/static/{{ i.goods.goods_picture }}"></li>
            <li class="col03">{{ i.goods.goods_name }}<br><em>{{ i.goods.goods_price }}元/500g</em></li>
            {#            <li class="col04">{% widthratio i.goods_number 1 500 %}g</li>#}
            <li class="col04">500g</li>
            <li class="col05">{{ i.goods.goods_price }}元</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="add fl" onclick="adddel(this,'+')">+</a>
                    <input type="text" class="num_show fl" value="{{ i.goods_number }}">
                    <a href="javascript:;" class="minus fl" onclick="adddel(this,'-')">-</a>
                </div>
            </li>
            <li class="col07">{% widthratio i.goods_number 1 i.goods.goods_price %}元</li>
            <li class="col08"><a href="javascript:;" onclick="deletegoods({{ i.goods.id }})">删除</a></li>
        </ul>
    {% endfor %}

    <ul class="settlements">
        <li class="col01"><input type="checkbox" name="" checked onclick="checkall(this)"></li>
        <li class="col02">全选</li>
        <li class="col03">合计(不含运费)：<span>¥</span><em></em><br>共计<b>{{ user.cart_set.count }}</b>件商品</li>
        <li class="col04"><a href="javascript:;" onclick="place_order()">去结算</a></li>
    </ul>
{% endblock %}

{% block other_footer %}
    <script>
        //刷新商品金额
        function refresh() {
            var goods = document.getElementsByClassName("cart_list_td");
            document.getElementsByClassName("total_count")[0].getElementsByTagName("em")[0].innerText = goods.length;
            var total_money = 0;
            for (i = 0, j = 0; i < goods.length; i++) {
                var money = parseFloat(goods[i].childNodes[9].innerText) * parseFloat(goods[i].getElementsByTagName("input")[1].value);
                goods[i].childNodes[13].innerText = money.toFixed(2) + "元";
                if (goods[i].getElementsByTagName("input")[0].checked == true) {
                    total_money += money;
                    j++;
                }
            }
            document.getElementsByClassName("settlements")[0].getElementsByTagName("b")[0].innerText = j;
            document.getElementsByClassName("settlements")[0].getElementsByTagName("em")[0].innerText = total_money.toFixed(2);
        }

        refresh()

        //删除商品
        function deletegoods(id) {
            var delhttp = new XMLHttpRequest();
            delhttp.open("delete", "", true);
            delhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            delhttp.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            delhttp.send("id=" + id);
            delhttp.onreadystatechange = function () {
                if (delhttp.readyState == 4 && delhttp.status == 200) {
                    document.getElementById(id).remove();
                    refresh();
                }
            }
        }

        //商品数量加减
        function adddel(obj, s) {
            var adhttp = new XMLHttpRequest();
            adhttp.open("put", "", true);
            adhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            adhttp.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            var el = obj.parentElement.parentElement.parentElement;
            var id = el.id;//商品的id
            var num_in = el.getElementsByTagName("input")[1];
            var num = parseInt(num_in.value);
            if (num > 0 && s == "-") {
                num -= 1;
            } else if (s == "+") {
                num += 1;
            }
            adhttp.send("id=" + id + "&num=" + num);
            adhttp.onreadystatechange = function () {
                if (adhttp.readyState == 4 && adhttp.status == 200) {
                    v = JSON.parse(adhttp.responseText)
                    console.log(v['data']);
                    num_in.value = v['data'];
                }
            }
            refresh()
        }

        //全选和取消全选
        function checkall(obj) {
            if (obj.checked == true) {
                v = true;
            } else {
                v = false;
            }
            var goods = document.getElementsByClassName("cart_list_td");
            for (i = 0; i < goods.length; i++) {
                goods[i].getElementsByTagName("input")[0].checked = v;
            }
            refresh()
        }

        //提交订单
        function place_order() {
            refresh();
            var goods = document.getElementsByClassName("cart_list_td");
            var data = new Array();
            for (i = 0; i < goods.length; i++) {
                if (goods[i].getElementsByTagName("input")[0].checked == true) {
                    id = goods[i].id;
                    num = goods[i].getElementsByTagName("input")[1].value;
                    if (id && num > 0) {
                        data.push({'id': id, 'num': num});
                    }
                }
            }
            data = JSON.stringify(data);
            aohttp = new XMLHttpRequest();
            aohttp.open("post", "", true);
            aohttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            aohttp.send("csrfmiddlewaretoken={{ csrf_token }}&data=" + data);
            aohttp.onreadystatechange = function () {
                if (aohttp.readyState == 4 && aohttp.status == 200) {
                    window.location.href = "place_order.html";
                }
            }

        }

    </script>
{% endblock %}

daydayseafood/buyer/templates/index.html
{% extends 'base.html' %}

{% block other_header %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}

{% block content %}
    {% include 'block/header.html' %}
    {% include 'block/search.html' %}

    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="/index.html">首页</a></li>
                <li class="interval">|</li>
                <li><a href="#">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for i in goods_type %}
                <li><a href="#{{ i.type_label }}">{{ i.type_description }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            <a href="#"><img src="/static/images/adv01.jpg"></a>
            <a href="#"><img src="/static/images/adv02.jpg"></a>
        </div>
    </div>
    {% for i in goods_type %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="{{ i.type_label }}">{{ i.type_description }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for j in i.goods_set.all|slice:":3" %}
                        <a href="/buyer/detail.html?id={{ j.id }}">{{ j.goods_name }}</a>
                    {% endfor %}
                </div>
                <a href="/buyer/list.html?type={{ i.type_description }}" class="goods_more fr" id="fruit_more">查看更多
                    ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="/static/{{ i.type_picture }}"></div>
                <ul class="goods_list fl">
                    {% for j in i.goods_set.all|slice:":4" %}
                        <li>
                            <h4><a href="/buyer/detail.html?id={{ j.id }}">{{ j.goods_name }}</a></h4>
                            <a href="/buyer/detail.html?id={{ j.id }}"><img src="/static/{{ j.goods_picture }}"></a>
                            <div class="prize">¥ {{ j.goods_price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

{% endblock %}

{% block other_footer %}
    <script type="text/javascript" src="/static/js/slide.js"></script>
    <script type="text/javascript">
        {#BCSlideshow('focuspic');#}
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>
{% endblock %}

daydayseafood/buyer/templates/user_center_order.html
{% extends "base.html" %}
{% block content %}
    {% include "block/header.html" %}
    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="user_center_info.html">· 个人信息</a></li>
                <li><a href="user_center_order.html" class="active">· 全部订单</a></li>
                <li><a href="user_center_site.html">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for one in order %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ one.order_date }}</li>
                    <li class="col02">订单号：{{ one.order_number }}</li>
                    <li class="col02 stress">{{ one.get_order_status_display }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for i in one.orderinfo_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="/static/{{ i.goods.goods_picture }}"></li>
                                    <li class="col02">{{ i.goods.goods_name }}<em>{{ i.goods.goods_price }}元/500g</em>
                                    </li>
                                    <li class="col03">{{ i.goods_count }}</li>
                                    <li class="col04"></li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td class="total" width="15%"></td>
                        {% if one.order_status == 1 %}
                            <td width="15%">待付款</td>
                            <td width="15%"><a href="javascript:;" onclick="place_order(this)" class="oper_btn">去付款</a>
                            </td>
                        {% elif one.order_status == 2 %}
                            <td width="15%">已付款</td>
                            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                        {% endif %}
                    </tr>
                    </tbody>
                </table>
            {% endfor %}

            <div class="pagenation">
                <a href="#">
                    <上一页
                </a>
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
                <a href="#">下一页></a>
            </div>
        </div>
    </div>
{% endblock %}

{% block other_footer %}
    <script>
        function total_pay() {
            var order_table = document.getElementsByTagName("table")
            for (i = 0; i < order_table.length; i++) {
                var total_money = 0
                var order_col = order_table[i].getElementsByClassName('col02')
                for (j = 0; j < order_col.length; j++) {
                    var price = parseFloat(order_col[j].firstElementChild.innerText)
                    var count = parseFloat(order_col[j].nextElementSibling.innerText)
                    var value = price * count
                    order_table[i].getElementsByClassName('col04')[j].innerText = value.toFixed(2) + "元"
                    total_money += value
                }
                document.getElementsByClassName("total")[i].innerText = total_money.toFixed(2) + "元"
            }
        }
        total_pay()
    </script>
{% endblock %}